# Generated by Django 3.0.5 on 2020-07-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_title', models.CharField(max_length=50)),
                ('cat_icon', models.ImageField(upload_to='cat_icons')),
                ('cat_ban', models.CharField(max_length=50)),
                ('cat_desc', models.TextField()),
                ('clr_url', models.CharField(max_length=50)),
                ('is_enable', models.BooleanField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catagories',
                'verbose_name_plural': 'Catagoriess',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('prod_img', models.ImageField(upload_to='products')),
                ('prod_desc', models.TextField()),
                ('prod_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2)),
                ('allow_to_attach_file', models.BooleanField()),
                ('is_mandatory_to_attach', models.BooleanField()),
                ('is_avail_to_sell', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Productss',
            },
        ),
        migrations.CreateModel(
            name='ProductsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=50)),
                ('reviewer_name', models.CharField(max_length=50)),
                ('text_of_review', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Productss',
            },
        ),
        migrations.CreateModel(
            name='RootCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic', models.CharField(max_length=50)),
                ('bluety_helth', models.CharField(max_length=50)),
                ('cosmetics', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'RootCatagory',
                'verbose_name_plural': 'RootCatagorys',
            },
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_title', models.CharField(choices=[('show', 'show'), ('hide', 'hide')], max_length=4)),
                ('cat_icon', models.ImageField(upload_to='cat_icons')),
                ('cat_ban', models.CharField(max_length=50)),
                ('cat_desc', models.TextField()),
                ('clr_url', models.CharField(max_length=50)),
                ('is_enable', models.BooleanField(max_length=50)),
                ('meta_key', models.CharField(max_length=50)),
                ('meta_desc', models.CharField(max_length=50)),
                ('par_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Catagory')),
            ],
            options={
                'verbose_name': 'SubCatagory',
                'verbose_name_plural': 'SubCatagorys',
            },
        ),
        migrations.CreateModel(
            name='Shippings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=50)),
                ('req_shipping', models.BooleanField()),
                ('price', models.IntegerField()),
                ('is_free', models.BooleanField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products')),
            ],
            options={
                'verbose_name': 'Shippings',
                'verbose_name_plural': 'Shippingss',
            },
        ),
        migrations.CreateModel(
            name='RelProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products')),
            ],
            options={
                'verbose_name': 'RelProducts',
                'verbose_name_plural': 'RelProductss',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubCatagory'),
        ),
        migrations.CreateModel(
            name='PriceInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('sell_price', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('is_inventory_track', models.BooleanField()),
                ('quantity_in_stock', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products')),
            ],
            options={
                'verbose_name': 'PriceInventory',
                'verbose_name_plural': 'PriceInventorys',
            },
        ),
        migrations.AddField(
            model_name='catagory',
            name='par_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RootCatagory'),
        ),
    ]
