# Generated by Django 3.0.5 on 2020-07-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'Catagory', 'verbose_name_plural': 'Catagory'},
        ),
        migrations.AlterModelOptions(
            name='priceinventory',
            options={'verbose_name': 'PriceInventory', 'verbose_name_plural': 'PriceInventory'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsreview',
            options={'verbose_name': 'ProductsReview', 'verbose_name_plural': 'ProductsReview'},
        ),
        migrations.AlterModelOptions(
            name='relproducts',
            options={'verbose_name': 'RelProducts', 'verbose_name_plural': 'RelProducts'},
        ),
        migrations.AlterModelOptions(
            name='rootcatagory',
            options={'verbose_name': 'RootCatagory', 'verbose_name_plural': 'RootCatagory'},
        ),
        migrations.AlterModelOptions(
            name='shippings',
            options={'verbose_name': 'Shippings', 'verbose_name_plural': 'Shippings'},
        ),
        migrations.AlterModelOptions(
            name='subcatagory',
            options={'verbose_name': 'SubCatagory', 'verbose_name_plural': 'SubCatagory'},
        ),
        migrations.RenameField(
            model_name='rootcatagory',
            old_name='bluety_helth',
            new_name='bleuty_health',
        ),
    ]
