# Generated by Django 3.0.5 on 2020-07-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200717_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootcatagory',
            old_name='bleuty_health',
            new_name='beauty_health',
        ),
    ]
