# Generated by Django 3.0.5 on 2020-07-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200717_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootcatagory',
            old_name='beauty_health',
            new_name='root_cat',
        ),
        migrations.RemoveField(
            model_name='rootcatagory',
            name='cosmetics',
        ),
        migrations.RemoveField(
            model_name='rootcatagory',
            name='electronic',
        ),
    ]
