# Generated by Django 3.0.5 on 2020-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200717_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='cat_title',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], max_length=4),
        ),
    ]
