# Generated by Django 3.0.5 on 2020-07-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200717_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='cat_ban',
        ),
        migrations.RemoveField(
            model_name='subcatagory',
            name='cat_ban',
        ),
    ]
