# Generated by Django 3.0.5 on 2020-07-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200717_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='relproducts',
            name='allow_to_attach_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SubCatagory'),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='is_avail_to_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='is_mandatory_to_attach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='prod_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='prod_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='prod_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='relproducts',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
