# Generated by Django 3.0.5 on 2020-07-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200717_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='cat_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='cat_icon',
            field=models.ImageField(null=True, upload_to='cat_icons'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='cat_title',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='clr_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='is_enable',
            field=models.BooleanField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='par_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RootCatagory'),
        ),
    ]
