# Generated by Django 3.0.5 on 2020-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200720_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='cat_icon',
            field=models.ImageField(default='cat_icons/AdminLTELogo.png', upload_to='cat_icons'),
        ),
    ]
