# Generated by Django 3.0.5 on 2020-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200722_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatagory',
            name='is_enable',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
