# Generated by Django 3.0.5 on 2020-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200722_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='cat_icon',
            field=models.ImageField(blank=True, default='cat_icons/AdminLTELogo.png', upload_to='cat_icons'),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='cat_icon',
            field=models.ImageField(blank=True, default='cat_icons/AdminLTELogo.png', upload_to='cat_icons'),
        ),
    ]
