# Generated by Django 3.0.5 on 2020-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200722_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatagory',
            name='cat_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='clr_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='meta_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
