# Generated by Django 3.0.5 on 2020-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200722_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatagory',
            name='cat_title',
            field=models.CharField(blank=True, choices=[('show', 'show'), ('hide', 'hide')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='is_enable',
            field=models.BooleanField(blank=True, default=True, max_length=50),
        ),
    ]
