# Generated by Django 3.0.5 on 2020-07-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200722_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippings',
            name='prod_id',
        ),
        migrations.AddField(
            model_name='products',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_free',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_inventory_track',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity_in_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='req_shipping',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sell_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='shipping_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='allow_to_attach_file',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SubCatagory'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_avail_to_sell',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_mandatory_to_attach',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PriceInventory',
        ),
        migrations.DeleteModel(
            name='Shippings',
        ),
    ]
