# Generated by Django 3.0.5 on 2020-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200724_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catagory',
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ManyToManyField(null=True, to='app.SubCatagory'),
        ),
    ]
