# Generated by Django 3.0.5 on 2020-07-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200724_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sell_price',
            field=models.IntegerField(null=True),
        ),
    ]
