# Generated by Django 3.0.5 on 2020-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200727_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='relproducts',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='catagory',
        ),
        migrations.AddField(
            model_name='relproducts',
            name='catagory',
            field=models.ManyToManyField(null=True, to='app.SubCatagory'),
        ),
    ]
