# Generated by Django 3.0.5 on 2020-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200727_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catagory',
            field=models.ManyToManyField(to='app.SubCatagory'),
        ),
        migrations.AlterField(
            model_name='relproducts',
            name='catagory',
            field=models.ManyToManyField(to='app.SubCatagory'),
        ),
    ]
