# Generated by Django 3.0.5 on 2020-07-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200727_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreview',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
    ]
