# Generated by Django 3.0.5 on 2020-07-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_productsreview_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsreview',
            name='prod_name',
        ),
        migrations.RemoveField(
            model_name='productsreview',
            name='profile',
        ),
    ]
