# Generated by Django 3.0.5 on 2020-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200727_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreview',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
