# Generated by Django 3.0.5 on 2020-07-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_productsreview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relproducts',
            name='allow_to_attach_file',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='is_avail_to_sell',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='is_mandatory_to_attach',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='prod_desc',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='prod_img',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='prod_name',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='prod_size',
        ),
        migrations.RemoveField(
            model_name='relproducts',
            name='sku',
        ),
    ]
