# Generated by Django 3.0.5 on 2020-07-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200727_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='relproducts',
            name='rel_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_related', to='app.Products'),
        ),
        migrations.AlterField(
            model_name='relproducts',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Products'),
        ),
    ]
