# Generated by Django 3.0.5 on 2020-07-28 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200727_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2020, 7, 28), null=True),
        ),
    ]
