# Generated by Django 3.0.5 on 2020-07-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200728_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(default='default.png', null=True, upload_to='products'),
        ),
    ]
