# Generated by Django 3.0.5 on 2020-07-30 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200728_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='arrival_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='productsreview',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
    ]
