# Generated by Django 3.0.5 on 2020-07-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200730_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsreview',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
    ]
